ignore:
  - "examples/14-moodle_id/targets.rb"
  # Security/YAMLLoad: Prefer using `YAML.safe_load` over `YAML.load`.
  - "lib/teuton/utils/configfile_reader.rb"
  - "lib/teuton/case_manager/case/play.rb"
  - "lib/teuton/case_manager/case/result/ext_array.rb"
  - "lib/teuton/case_manager/case/result/result.rb"
  - "lib/teuton/case_manager/dsl.rb"
  - "lib/teuton/check/dsl.rb"
  - "lib/teuton/check/laboratory.rb"
  - "lib/teuton/readme/dsl.rb"
  - "lib/teuton/readme/readme.rb"
  - "lib/teuton/report/formatter/csv_formatter.rb"
  #- "lib/teuton/report/formatter/html_formatter.rb"
  - "private/**/*"
  - "test/manual/**/*"
