ignore:
  - "lib/teuton/check/dsl.rb"
  - "lib/teuton/check/laboratory.rb"
  - "lib/teuton/check/show.rb"
  - "lib/teuton/readme/dsl.rb"
  - "lib/teuton/readme/readme.rb"
  - "lib/teuton/report/formatter/csv_formatter.rb"
  - "lib/teuton/report/formatter/html_formatter.rb"
  - "lib/teuton/report/formatter/xml_formatter.rb"
  - "private/**/*"
  - "test/manual/**/*"
